version: '3.8'

services:
  db:
    image: mysql
    container_name: DatabaseZeroToExpertJava
    restart: always
    environment:
      MYSQL_DATABASE: ZeroToExpertJavaDatabase
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: user1
      MYSQL_PASSWORD: haslo1
    ports:
      - 3306:3306
    expose:
      - 3306
#  myapp:
#    build:
#      dockerfile: Dockerfile
#    ports:
#      - 8080:8080
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ZeroToExpertJavaDatabase
#      SPRING_DATASOURCE_USERNAME: user1
#      SPRING_DATASOURCE_PASSWORD: haslo1